import type { Organization } from "./orgTypes";

export const MOCK_ORGS: Organization[] = [
  {
    id: "org1",
    name: "Ravi Kumar Properties",
    type: "individual",
    address: "14, 3rd Cross, Koramangala 5th Block",
    city: "Bangalore",
    phone: "+91 98765 00001",
    email: "ravi@ravikumarproperties.in",
    logoInitials: "RK",
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=80&h=80&fit=crop&auto=format",
    plan: "growth",
    propertyIds: ["p1", "p2", "p3"],
    ownerId: "o1",
    createdAt: "2024-01-15",
    members: [
      {
        id: "m1",
        name: "Ravi Kumar",
        email: "ravi@ravikumarproperties.in",
        phone: "+91 98765 00001",
        role: "owner",
        assignedProperties: [],
        status: "active",
        joinedAt: "2024-01-15",
      },
      {
        id: "m2",
        name: "Sunita Devi",
        email: "sunita@ravikumarproperties.in",
        phone: "+91 98765 00002",
        role: "admin",
        assignedProperties: [],
        status: "active",
        joinedAt: "2024-02-01",
      },
      {
        id: "m3",
        name: "Ramu Electrician",
        email: "ramu@gmail.com",
        role: "caretaker",
        assignedProperties: ["p1"],
        status: "active",
        joinedAt: "2024-03-10",
      },
      {
        id: "m4",
        name: "Pradeep Shetty",
        email: "pradeep.ca@gmail.com",
        role: "accountant",
        assignedProperties: [],
        status: "invited",
        joinedAt: "",
        invitedAt: "2026-04-18T10:00:00.000Z",
      },
    ],
  },
  {
    id: "org2",
    name: "Nova Stays Pvt Ltd",
    type: "company",
    gstin: "29AADCN1234F1Z5",
    cin: "U55101KA2023PTC180001",
    address: "72, 1st Floor, Indiranagar 100ft Road",
    city: "Bangalore",
    phone: "+91 80 4523 9900",
    email: "ops@novastays.in",
    website: "https://novastays.in",
    logoInitials: "NS",
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=80&h=80&fit=crop&auto=format",
    plan: "enterprise",
    propertyIds: ["np1", "np2"],
    ownerId: "o2",
    createdAt: "2023-08-20",
    members: [
      {
        id: "m5",
        name: "Vikram Nair",
        email: "vikram@novastays.in",
        phone: "+91 98001 00005",
        role: "owner",
        assignedProperties: [],
        status: "active",
        joinedAt: "2023-08-20",
      },
      {
        id: "m6",
        name: "Deepa Menon",
        email: "deepa@novastays.in",
        role: "manager",
        assignedProperties: ["p1"],
        status: "active",
        joinedAt: "2023-09-01",
      },
      {
        id: "m7",
        name: "Rahul Ops",
        email: "rahul.ops@novastays.in",
        role: "manager",
        assignedProperties: ["p2"],
        status: "active",
        joinedAt: "2023-09-15",
      },
      {
        id: "m8",
        name: "Accounts Team",
        email: "accounts@novastays.in",
        role: "accountant",
        assignedProperties: [],
        status: "inactive",
        joinedAt: "2024-01-01",
      },
    ],
  },
];

/** The org linked to the currently logged-in demo owner (Ravi Kumar) */
export const CURRENT_ORG = MOCK_ORGS[0];
